
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: eat_then_development


test:
  <<: *default
  database: eat_then_test


production:
  <<: *default
  database: eat_then_production
  username: eat_then
  password: <%= ENV['EAT_THEN_DATABASE_PASSWORD'] %>
